<?php include_once __DIR__ . '/header-collaboration.php'?>
<?php include_once __DIR__ . '/../templates/kanban-view.php'?>
<?php include_once __DIR__ . '/../templates/task-form.php'?>
<?php include_once __DIR__ . '/../templates/project-form.php'?>
<?php include_once __DIR__ . '/../templates/collaborator-form.php'?>
<?php include_once __DIR__ . '/../templates/assignments-form.php'?>
<?php include_once __DIR__ . '/../templates/comment-form.php'?>
<?php include_once __DIR__ . '/footer-dashboard.php'?>
<?php $script = "<script src='build/js/utils.js'></script>";?>
<?php $script .= "<script src='build/js/gets.js'></script>";?>
<?php $script .= "<script src='build/js/assignments.js'></script>";?>
<?php $script .= "<script src='build/js/collaborators.js'></script>";?>
<?php $script .= "<script src='build/js/comments.js'></script>";?>
<?php $script .= "<script src='build/js/collaboration-kanban.js'></script>";?>
<?php $script .= "<script src='build/js/kanban-view.js'></script>";?>
<?php $script .= "<script src='build/js/alert.js'></script>";?>
<?php $script .= "<script src='build/js/tasks.js'></script>";?>
<?php $script .= "<script src='build/js/calendar.js'></script>";?>